config/routes.rb
Rails.application.routes.draw do
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "invoice", to: "checkout#invoice", as: "checkout_invoice"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  devise_for :users
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/index"
  # get 'categories/index'
  # get 'categories/show'
  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: %i[index show]
  resources :cart, only: %i[create destroy]
  resources :searches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :category_name, presence: true, uniqueness: true

  def name
    category_name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :product_order

  validates :total_price, :tax, presence: true

  validates :total_price, :tax, numericality: { only_float: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  # has_one :product_order

  validates :product_name, :price, :description, presence: true

  validates :price, numericality: true

  has_one_attached :image
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # Add params[:id] product to the cart
  def create
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id

      product = Product.find(id)

      flash[:notice] = "Added Item #{product.product_name} to Cart."
    end
    redirect_to root_path
  end
  # Automagically load the associated view: app/cart/create.html.erb

  # DELETE /cart/:id
  # Remove product from the cart
  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)

    product = Product.find(id)

    flash[:delete_notice] = "Removed Item #{product.product_name} from Cart."
    redirect_to root_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  # POST /checkout/create
  # before_action :authenticate_user!
  # A product id will be in the params hash: params[:product_id]
  def create
    # Establish a connection with Stripe and then redirect user to the payment screen.
    prov_id = params[:province_id]
    province = Province.find(prov_id)

    line_items = session[:shopping_cart].map do |cart_item|
      product = Product.find(cart_item)
      {
        name:        product.product_name,
        description: product.description,
        amount:      product.price,
        currency:    "cad",
        quantity:    1
      }
    end
    sum = session[:shopping_cart].sum { |id| Product.find(id).price }
    logger.debug("Sum is #{sum}")

    line_items << {
      name:     "HST",
      amount:   sum * province.tax_rate / 100,
      currency: "cad",
      quantity: 1

    }

    # establish a connection to Stripe using the stripe gem

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      success_url:
                            checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url:           checkout_cancel_url,
      line_items:           line_items
    )

    new_order = current_user.orders.create(total_price: sum, tax: sum * province.tax_rate / 100,
      status: "Incomplete", payment_id: @session.id)
    logger.debug(new_order.errors.messages)

    # new_order.

    respond_to do |format|
      format.js # render app/views/checkout/create.js.erb
    end
  end

  def success
    # We took the customers money
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    # @payment_status = Stripe::PaymentIntent.retrieve(@session.payment_status)

    logger.debug(@payment_intent)
    order = Order.find_by(payment_id: @session.id)
    order.status = "Completed"
    order.save

    # new_order.status = "Completed"
    # new_order.status = "Completed" if @payment_intent.payment_status == "paid"
  end

  def cancel
    # Something went wrong with the payment.
  end

  def invoice
    @province = Province.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.includes(:category)
                       .order("product_name")
                       .limit(8)

    @categories = Category.all

    # @companies = Company.all
  end

  # def add_breadcrumb
  #   add_breadcrumb "Home", :root_path
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).order("product_name").page(params[:page])
    add_breadcrumb("Products", nil, true)
    @recently_updated = Product.includes(:category).order("created_at")
    @recently_created = Product.includes(:category).order("updated_at")
  end
  # def index
  #   @products = Product.search(params[:search]).page(params[:page])
  # end

  def show
    @product = Product.find(params[:id])
    add_breadcrumb("Products", products_path)
    add_breadcrumb(@product.product_name, nil)
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    category_search = params[:category_id].to_i
    @products = if category_search == -99
                  Product.where("product_name LIKE ?", wildcard_search)
                else
                  Product.where("product_name LIKE ?", wildcard_search)
                         .where("category_id == ?", category_search)
                end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about/index.html.erb
<h1 class="title is-1">About Page</h1>
<h3 class="title is-3">HalfCutAngling_FinalProject</h3>
<section >
<h4 class="title is-4">Description:</h4>
<section class="about" >
<p>
HCA is a fishing and outdoorsman outfitter company that wants to update its website to be able
 to reach a larger market and making it easier for customers to make orders and receive their outdoor gear.
  I will be using the Ruby on Rails web framework to build a dynamic content management system to categorize and display HCA’s products,
   allowing for easy navigation between all pages and products for customers to browse.
</p>
<p>
I will be implementing the ActiveAdmin dashboard for administrative CRUD functionality.
This will allow an admin account to have complete control over the data.
For this project, I will be using a custom CSV file to upload product data, generating products and categories to mirror that of HCA’s inventory.
</p>
</section>

<h2 class="title is-2">Database Relationships</h2>
<ol class="ml-5">
  <li>Product-Category = many-to-one</li>
  <li>Product-Orders = many-to-many</li>
  <li>Order-Customer = one-to-many</li>
  <li>Province-Customer = one-to-many</li>
</ol>

</section>

app/views/checkout/cancel.html.erb
<h1>WE WANTED YOUR MONEY BUT IT DIDN'T WORK</h1>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function(result){
  console.log(result.error.message);
});

app/views/checkout/invoice.html.erb
  <h2 class="title is-2"> Invoice</h2>
<section class="cat">

      <ul>
          <li>
            Cart 🛒
            <% if cart.present? %>
              <sup><%= cart.size %></sup>
              <ul class="cart">
                <% cart.each do |product| %>
                  <li>
                    <%= number_to_currency product.price / 100.0 %> - <%= product.product_name %> <%= link_to '❌', cart_path(product), method: :delete %>
                  </li>
                <% end %>
                <li>
                  Total = <%= number_to_currency session[:shopping_cart].sum { |id| Product.find(id).price } / 100 %>
                </li>
            <% end %>
          </li>
      </ul>

                <%= form_with url: checkout_create_path, remote: true do  %>
                  <%= select_tag("province_id", options_from_collection_for_select(provinces_for_select, "id", "name", "tax_rate"))%>
                  <%= button_tag "Buy Now" %>
		            <% end %>


</section>

app/views/checkout/success.html.erb
<h1>SUCCESS! THANK YOU FOR YOUR PURCHASE!</h1>

<%= debug @session %>
<%= debug @payment_intent %>

app/views/contact/index.html.erb
<h1>Please feel free to contact us with any questions!</h1>
<p>Email: m.cook2434@gmail.com</p>
<p>Github: <a href="https://github.com/Hands34">Hands34</a></p>
<p>Facebook: <a href="https://www.facebook.com/mitchell.cook.92">Mitchell Cook</a></p>

app/views/home/index.html.erb
<div class="container mt-5">
  <div class="notification is-primary">
    <ul class="ml-5 is-flex">
      <% @categories.each do |category| %>
        <li class="mx-5">
          <strong>
            <%= link_to category.category_name, category %>
          </strong>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="columns">
  <div class="column">
    <h2 class="title is-4">Featured Products</h2>
      <div>
        <ul class="ml-5">
          <%= render @products %>
        </ul>
      </div>
  </div>
</div>