config/routes.rb
Rails.application.routes.draw do
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "invoice", to: "checkout#invoice", as: "checkout_invoice"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  devise_for :users
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/index"
  # get 'categories/index'
  # get 'categories/show'
  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: %i[index show]
  resources :cart, only: %i[create destroy]
  resources :searches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :category_name, presence: true, uniqueness: true

  def name
    category_name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :product_order

  validates :total_price, :tax, presence: true

  validates :total_price, :tax, numericality: { only_float: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  # has_one :product_order

  validates :product_name, :price, :description, presence: true

  validates :price, numericality: true

  has_one_attached :image
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # Add params[:id] product to the cart
  def create
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id

      product = Product.find(id)

      flash[:notice] = "Added Item #{product.product_name} to Cart."
    end
    redirect_to root_path
  end
  # Automagically load the associated view: app/cart/create.html.erb

  # DELETE /cart/:id
  # Remove product from the cart
  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)

    product = Product.find(id)

    flash[:delete_notice] = "Removed Item #{product.product_name} from Cart."
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    add_breadcrumb("Categories")
  end

  def show
    @category = Category.find(params[:id])
    add_breadcrumb("Categories", categories_path)
    add_breadcrumb(@category.category_name)
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  # POST /checkout/create
  # before_action :authenticate_user!
  # A product id will be in the params hash: params[:product_id]
  def create
    # Establish a connection with Stripe and then redirect user to the payment screen.
    prov_id = params[:province_id]
    province = Province.find(prov_id)

    line_items = session[:shopping_cart].map do |cart_item|
      product = Product.find(cart_item)
      {
        name:        product.product_name,
        description: product.description,
        amount:      product.price,
        currency:    "cad",
        quantity:    1
      }
    end
    sum = session[:shopping_cart].sum { |id| Product.find(id).price }
    logger.debug("Sum is #{sum}")

    line_items << {
      name:     "HST",
      amount:   sum * province.tax_rate / 100,
      currency: "cad",
      quantity: 1

    }

    # establish a connection to Stripe using the stripe gem

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      success_url:
                            checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}",
      cancel_url:           checkout_cancel_url,
      line_items:           line_items
    )

    new_order = current_user.orders.create(total_price: sum, tax: sum * province.tax_rate / 100,
      status: "Incomplete", payment_id: @session.id)
    logger.debug(new_order.errors.messages)

    # new_order.

    respond_to do |format|
      format.js # render app/views/checkout/create.js.erb
    end
  end

  def success
    # We took the customers money
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    # @payment_status = Stripe::PaymentIntent.retrieve(@session.payment_status)

    logger.debug(@payment_intent)
    order = Order.find_by(payment_id: @session.id)
    order.status = "Completed"
    order.save

    # new_order.status = "Completed"
    # new_order.status = "Completed" if @payment_intent.payment_status == "paid"
  end

  def cancel
    # Something went wrong with the payment.
  end

  def invoice
    @province = Province.all
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.includes(:category)
                       .order("product_name")
                       .limit(8)

    @categories = Category.all

    # @companies = Company.all
  end

  # def add_breadcrumb
  #   add_breadcrumb "Home", :root_path
  # end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.includes(:category).order("product_name").page(params[:page])
    add_breadcrumb("Products", nil, true)
    @recently_updated = Product.includes(:category).order("created_at")
    @recently_created = Product.includes(:category).order("updated_at")
  end
  # def index
  #   @products = Product.search(params[:search]).page(params[:page])
  # end

  def show
    @product = Product.find(params[:id])
    add_breadcrumb("Products", products_path)
    add_breadcrumb(@product.product_name, nil)
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    category_search = params[:category_id].to_i
    @products = if category_search == -99
                  Product.where("product_name LIKE ?", wildcard_search)
                else
                  Product.where("product_name LIKE ?", wildcard_search)
                         .where("category_id == ?", category_search)
                end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
  <aside>

    <h3><strong><%= link_to category.category_name, category %></strong></h3>


  </aside>

app/views/categories/index.html.erb
  <h2 class="title is-2"> Categories </h2>
<section class="cat">
  <ul>
    <%= render @categories %>
  </ul>
</section>

app/views/categories/show.html.erb
<% content_for(:html_title) { @category.category_name } %>
<h2 class="title is-2"><%= @category.category_name %></h2>

<p>
  This category has <%= @category.products.count %> products in it.
</p>

<ul>
  <% @category.products.each do |product| %>
    <li><%= link_to product.product_name, product %></li>
  <% end %>
</ul>

app/views/products/_product.html.erb
  <section class="product"><aside>
    <% if product.image.present? %>
      <p><%= image_tag product.image  %></p>
    <% end %>
    <h3><strong><%= link_to product.product_name, product %></strong></h3>
    <p><strong>Price:</strong> <%= number_to_currency product.price / 100.0 %></p>


    <p><%= truncate(product.description, length: 100) %> <%= link_to "more", product %></p>
    <%# <%= simple_format truncate((h(product.description) + link_to("Read More", product_path(product))), length: 400, separator: ' ') %>
    <%# <%= product.description %>

    <% if cart.include?(product) %>
      <%= button_to cart_path(product), method: :delete do %>
        ❌Remove From Cart
      <% end %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do %>
      <%= hidden_field_tag(:id, product.id) %>
      <%= button_tag '➕Add to Cart' %>
      <% end %>
    <% end %>
  </aside></section>

app/views/products/index.html.erb
<h1 class="title is-3">Available Products</h1>
<div>
  <ul class="ml-5">
    <%= render @products %>
  </ul>
  <%= paginate(@products)%>
</div>

app/views/products/search.html.erb
<p class="mb-5">Found <%= pluralize(@products.count, 'Product') %> when searching for: <%= params[:keywords] %></p>

<ul>
  <%= render @products %>
</ul>

app/views/products/show.html.erb
<% content_for(:html_title) { @product.product_name } %>
  <div >
  <aside class="p_show">
    <% if @product.image.present? %>
      <p><%= image_tag @product.image  %></p>
    <% end %>
    <h2><strong><%= link_to @product.product_name, @product %></strong></h2>
    <p><strong>Price:</strong> <%= number_to_currency @product.price / 100.0 %></p>


    <p><%= @product.description %></p>
    <%# <%= simple_format truncate((h(product.description) + link_to("Read More", product_path(product))), length: 400, separator: ' ') %>
    <%# <%= product.description %>

    <% if cart.include?(@product) %>
      <%= button_to cart_path(@product), method: :delete do %>
        ❌Remove From Cart
      <% end %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do %>
      <%= hidden_field_tag(:id, @product.id) %>
      <%= button_tag '➕Add to Cart' %>
      <% end %>
    <% end %>
    </aside>
  </div>