config/routes.rb
Rails.application.routes.draw do
  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "invoice", to: "checkout#invoice", as: "checkout_invoice"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
  end

  devise_for :users
  get "contact/index"
  get "about/index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get "home/index"
  # get 'categories/index'
  # get 'categories/show'
  # get 'products/index'
  # get 'products/show'
  resources :products, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :categories, only: %i[index show]
  resources :cart, only: %i[create destroy]
  resources :searches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :category_name, presence: true, uniqueness: true

  def name
    category_name
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one :product_order

  validates :total_price, :tax, presence: true

  validates :total_price, :tax, numericality: { only_float: true }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  # has_one :product_order

  validates :product_name, :price, :description, presence: true

  validates :price, numericality: true

  has_one_attached :image
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # Add params[:id] product to the cart
  def create
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id

      product = Product.find(id)

      flash[:notice] = "Added Item #{product.product_name} to Cart."
    end
    redirect_to root_path
  end
  # Automagically load the associated view: app/cart/create.html.erb

  # DELETE /cart/:id
  # Remove product from the cart
  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)

    product = Product.find(id)

    flash[:delete_notice] = "Removed Item #{product.product_name} from Cart."
    redirect_to root_path
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.includes(:category)
                       .order("product_name")
                       .limit(8)

    @categories = Category.all

    # @companies = Company.all
  end

  # def add_breadcrumb
  #   add_breadcrumb "Home", :root_path
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= yield(:html_title) if content_for?(:html_title) %> HalfCut Angling Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <section class="section">
    <div class="container">
    <header class="header">
      <nav>
        <%= link_to image_tag("HCA.jpg", width: 60), root_path %>
        <ul>
          <li>
            Cart 🛒
            <% if cart.present? %>
              <sup><%= cart.size %></sup>
              <ul class="cart">
                <% cart.each do |product| %>
                  <li>
                    <%= number_to_currency product.price / 100.0 %> - <%= product.product_name %> <%= link_to '❌', cart_path(product), method: :delete %>
                  </li>
                <% end %>

                  <%= link_to 'Checkout', checkout_invoice_path %>
              </ul>
            <% end %>
          </li>
        </ul>
          <p class="navbar-text float-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
      </nav>

      <h1 class="title is-1"><%= link_to 'HalfCut Angling Store', root_path %></h1>

    </header>
    <%= render partial: 'shared/breadcrumbs' %>

          <%= form_with(url: search_products_path, method: :get, local: true) do %>
        <div class="field is-grouped mb-5">
          <div class="control is-expanded">
            <%= text_field_tag(:keywords, nil, class: "input", placeholder: 'Search For Products') %>
          </div>
          <div class="select is-primary">
            <%= select_tag("category_id", options_from_collection_for_select(categories_for_select, "id", "category_name"), placeholder: 'All')%>
          </div>
          <div class="control">
            <%= submit_tag("Search", class: "button is-primary") %>
          </div>
        </div>
      <% end %>
      <% if flash[:notice] %>
        <p><%= flash[:notice]%></p>
      <% end %>
      <% if flash[:delete_notice] %>
        <p><%= flash[:delete_notice]%></p>
      <% end %>
      <section>
        <%= yield %>
      </section>
      <%= render partial: 'shared/footer' %>
    </div>
  </section>
  </body>
</html>

app/views/shared/_breadcrumbs.html.erb
<nav class="breadcrumb has-arrow-separator" aria-label="breadcrumbs">
  <ul>
    <li><a href="/">Home</a></li>
    <% @breadcrumbs.each do |breadcrumb| %>
      <% if breadcrumb[:path].nil? %>
        <li>
          <%=  breadcrumb[:label] %>
        </li>
      <% else %>
        <li>
          <%= link_to breadcrumb[:label], breadcrumb[:path] %>
        </li>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/shared/_footer.html.erb
<hr>
<footer class="footer">
<div class="content has-text-centered">
  <ul class="mt-5">
    <li><%= link_to 'Home' , root_path %></li>
    <li><%= link_to 'All Products', products_path %></li>
    <li><%= link_to 'All Categories', categories_path %></li>
    <li><%= link_to 'About', about_index_path %></li>
    <li><%= link_to 'Contact Us', contact_index_path %></li>
  </ul>
  <p><em>CopyWrong HalfCut Angling 2020</em></p>
  </div>
</footer>